spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USERNAME:orders}
    password: ${DB_PASSWORD:orders}
  jpa:
    open-in-view: false
    hibernate:
        ddl-auto: validate
  flyway:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: never

clients:
  inventory:
    base-url: ${INVENTORY_BASE_URL:http://localhost:8081}
    reservations-path: /api/v1/inventory/reservations

server:
  port: 8080
